In [1]:
import numpy as np
import cv2

retangulo = cv2.getStructuringElement(cv2.MORPH_RECT,(5,5))
elipse = cv2.getStructuringElement(cv2.MORPH_ELLIPSE,(5,5))
cruz = cv2.getStructuringElement(cv2.MORPH_CROSS,(5,5))

print("Retangulo")
print(retangulo)
print("\n")
print("Elispe")
print(elipse)
print("\n")
print("Cruz")
print(cruz)

Retangulo
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


Elispe
[[0 0 1 0 0]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [0 0 1 0 0]]


Cruz
[[0 0 1 0 0]
 [0 0 1 0 0]
 [1 1 1 1 1]
 [0 0 1 0 0]
 [0 0 1 0 0]]
